---
# tasks file for wordpress

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  become: yes
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update default Apache config
  become: yes
  template:
    src: "{{ role_path }}/templates/000-default.conf"
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart apache

- name: Create WordPress config file
  become: yes
  template:
    src: "{{ role_path }}/templates/wp-config.php"
    dest: /var/www/wordpress/wp-config.php

- name: Update WordPress config file
  become: yes
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: "(.*)db_name_here(.*)", line: '\1{{ wp_db_name }}\2' }
    - { regexp: "(.*)db_username_here(.*)", line: '\1{{ mysql_user_name }}\2' }
    - { regexp: "(.*)db_password_here(.*)", line: '\1{{ mysql_user_password }}\2' }
    - { regexp: "(.*)wp_ip_here(.*)", line: "define( 'DB_HOST', '{{ wp_db_host }}' );" }

- name: Create .htaccess WordPress
  become: yes
  template:
    src: "{{ role_path }}/templates/.htaccess"
    dest: /var/www/wordpress/.htaccess

- name: Update right & permissions
  become: yes
  file: dest=/var/www/wordpress owner=www-data group=www-data mode=0775 recurse=yes
